import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import DormList from "@/components/dormList";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Middlebury Dorms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}> Middlebury Dorms</h1>

          <section className={styles.funFacts}>
            <div className={styles.funFacts}>
              <p>
                🏫 Did you know Battell is said to be turned into a museum, once
                the new dorm opens?
              </p>
              <p>🎉 Giffords 5th floor lounge has amazing sunset views!</p>
              <p>🌲 Forest has personal sinks adjoining two single rooms. </p>
            </div>
            <Image
              className={styles.funImage}
              src="/dorms.jpg"
              alt="Middlebury Dorms"
              width={300}
              height={200}
            />
          </section>

          {/* Dorm Sections */}
          <section className={styles.dormSection}>
            <h2 className={styles.dormHeading}>First Year Dorms</h2>
            <DormList dormFilter="first" />
          </section>

          <section className={styles.dormSection}>
            <h2 className={styles.dormHeading}>Second Year Dorms</h2>
            <DormList dormFilter="second" />
          </section>
          <section className={styles.dormSection}>
            <h2 className={styles.dormHeading}>Senior Year Dorms</h2>
            <DormList dormFilter="senior" />
          </section>
        </main>

        <footer className={styles.footer}>
          {/* <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples */}
          {/* </a> */}
          {/* <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a> */}
        </footer>
      </div>
    </>
  );
}
